version: '3'

tasks:
  podman_build:
    desc: Build the Docker image
    cmds:
      - podman build --tag highs-san -f ./Dockerfile

  podman_run:
    desc: Run the Docker image
    cmds:
      - mkdir -p ${HOME}/highs-output
      - podman run --rm -it -v ${HOME}/highs-output:/root/highs-output localhost/highs-san:latest bash
